# Generated by Django 5.2.3 on 2025-06-25 08:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentoption_delete_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentoption',
            name='currency_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentoption',
            name='currency_uk',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentoption',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentoption',
            name='description_uk',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentoption',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentoption',
            name='title_uk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
