# Generated by Django 5.2.3 on 2025-06-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentoption_currency_en_paymentoption_currency_uk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentoption',
            name='title',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
