# Generated by Django 5.2.7 on 2025-10-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact_location_en_contact_location_uk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='no_social',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='use_telegram',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='use_viber',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='use_whatsapp',
        ),
    ]
