# Generated by Django 5.2.7 on 2025-10-15 08:19

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_remove_volunteerapplication_no_social_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('social_links', models.TextField()),
                ('company_info', models.TextField()),
                ('contacted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partnership Application',
                'verbose_name_plural': 'Partnership Applications',
                'ordering': ['-contacted_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='volunteerapplication',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Volunteer Application', 'verbose_name_plural': 'Volunteer Applications'},
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='social_link',
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='social_links',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
