# Generated by Django 5.2.7 on 2025-10-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_partnershipapplication_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnershipapplication',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Partnership Application', 'verbose_name_plural': 'Partnership Applications'},
        ),
        migrations.RenameField(
            model_name='partnershipapplication',
            old_name='contacted_at',
            new_name='submitted_at',
        ),
    ]
