# Generated by Django 5.2.3 on 2025-06-23 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="members/"),
                ),
                ("position", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999999'. Up to 15wefwefwefwf digits allowed.",
                                regex="^\\+?1?\\d{12}$",
                            )
                        ],
                    ),
                ),
                ("instagram", models.CharField(blank=True, max_length=50, null=True)),
                ("telegram", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
