# Generated by Django 5.2.3 on 2025-06-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='support_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default=1, help_text='Auto generated from title', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
