# Generated by Django 5.2.3 on 2025-06-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contactmessage_volunteerapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='name',
            new_name='first_name',
        ),
    ]
