# Generated by Django 5.2.3 on 2025-06-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_contact_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='location_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='location_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
