# Generated by Django 5.2.3 on 2025-06-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='title_uk',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
