# Generated by Django 5.2.3 on 2025-08-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_description_en_report_description_uk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportimage',
            name='image',
            field=models.ImageField(upload_to='reports/'),
        ),
    ]
