# Generated by Django 5.2.7 on 2025-10-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_reportimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportimage',
            name='title',
        ),
    ]
