# Generated by Django 5.2.7 on 2025-10-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_reportvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('New', 'New'), ('Events', 'Events'), ('Announcement', 'Announcement')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
