# Generated by Django 5.2.7 on 2025-10-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('News', 'News'), ('Events', 'Events'), ('Announcement', 'Announcement')], max_length=100),
        ),
    ]
