# Generated by Django 5.2.7 on 2025-10-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_report_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='description',
            new_name='description1',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='description_en',
            new_name='description1_en',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='description_uk',
            new_name='description1_uk',
        ),
        migrations.AddField(
            model_name='report',
            name='description2',
            field=models.TextField(blank=True, help_text='Unrequired', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='description2_en',
            field=models.TextField(blank=True, help_text='Unrequired', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='description2_uk',
            field=models.TextField(blank=True, help_text='Unrequired', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='preview_image',
            field=models.ImageField(default=1, upload_to='reports/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='short_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='short_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='short_description_uk',
            field=models.TextField(null=True),
        ),
    ]
