# Generated by Django 5.2.7 on 2025-10-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_rename_description_report_description1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description_image',
            field=models.ImageField(blank=True, help_text='Unrequired', null=True, upload_to='reports/'),
        ),
    ]
