# Generated by Django 5.2.3 on 2025-06-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('programs', '0002_category_program_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programimage',
            name='title',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
