# Generated by Django 5.2.3 on 2025-06-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_programimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto generated from title', null=True, unique=True),
        ),
    ]
